{{- if and .Values.controller.stats.enabled .Values.controller.metrics.enabled .Values.controller.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "nginx-ingress.controller.fullname" . }}
  {{- if .Values.controller.metrics.serviceMonitor.namespace }}
  namespace: {{ .Values.controller.metrics.serviceMonitor.namespace }}
  {{- end }}
  labels:
    app.kubernetes.io/name: {{ template "nginx-ingress.name" . }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: {{ template "nginx-ingress.controller.fullname" . }}
    {{- if .Values.controller.metrics.serviceMonitor.additionalLabels }}
{{ toYaml .Values.controller.metrics.serviceMonitor.additionalLabels | indent 4 }}
    {{- end }}
spec:
  endpoints:
    - port: metrics
      interval: 30s
      {{- if .Values.controller.metrics.serviceMonitor.honorLabels }}
      honorLabels: true
      {{- end }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "nginx-ingress.name" . }}
      app.kubernetes.io/component: {{ template "nginx-ingress.controller.fullname" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      {{- if .Values.controller.podLabels }}
{{ toYaml .Values.controller.podLabels | indent 6 }}
      {{- end }}
{{- end }}
